<?php

namespace AppBundle\Repository;

/**
 * EventHourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventHourRepository extends \Doctrine\ORM\EntityRepository
{
}
